version: '3'
services:
  api1:
    build:
      context: ./api1
    ports:
      - '3001:3001'
    networks:
      - api_network

  api2:
    build:
      context: ./api2
    ports:
      - '3002:3002'
    networks:
      - api_network

networks:
  api_network:
